# Generated by Django 5.1.1 on 2024-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.URLField()),
                ('linkedn_url', models.URLField()),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=150)),
                ('state_name', models.CharField(max_length=150)),
                ('city_name', models.CharField(max_length=150)),
                ('current_employee_count', models.BigIntegerField()),
                ('total_employee_count', models.BigIntegerField()),
                ('size_range', models.CharField(max_length=10)),
            ],
        ),
    ]
